### ISSUE TITLE
Movement of the avatar following the body in the video 

### ISSUE THREAD

**Issue by dantonioangela** [GanniPiece/MetU#1]
Hi, 
thank you for this great project! 
I was wondering if it is possible to make the avatar move with the shape of the human in the video and how.
I provide you an example of what i mean.
![preview_capture_v2](https://user-images.githubusercontent.com/48484241/213406510-ef149e9f-1822-431e-adac-21c5ca3290f5.gif)

**Comment by GanniPiece** [comment]
Sure, the position of the character relative to the image can be obtained by the `POSE_LANDMARKS`. 

https://google.github.io/mediapipe/solutions/holistic#pose_landmarks
