### ISSUE TITLE
Use the code in another avatar

### ISSUE THREAD

**Issue by Hakoware** [GanniPiece/MetU#4]
Hi I am trying to implement your project but using a smplx (humanoid) avatar, but it fails to replicate the correct movement. Your project is intended only for that avatar (unity chan)? how could I do it to be able to use another avatar?

**Comment by GanniPiece** [comment]
The humanoid skeleton is not defined in unified as far as I know. It depends on the creator/animator of the avatars.
To deal with this, I think you could first make sure the coordination or the rotation on each joint on your avatar. 
Hope that it helps you.

**Comment by chopin1998** [comment]
i got other avatar, but weird ... seems joint name not matched..

https://user-images.githubusercontent.com/643792/222693743-698e9b9e-ce1f-4eb2-ac67-f0bbc7a5af2d.mp4

**Comment by GanniPiece** [comment]
Hi, @chopin1998 I'm not familiar with smplx models. Do you have any example model that I can try? Or any document that refer to the smplx ?

**Comment by Hakoware** [comment]
Hi! @GanniPiece  here is the link where you can find the documentation and download it 
https://smpl-x.is.tue.mpg.de
I hope it helps you

**Comment by Hakoware** [comment]
Hi! @GanniPiece  here is the link where you can find the documentation and download it 
https://smpl-x.is.tue.mpg.de
I hope it helps you
